### ISSUE TITLE
[problem]http status 500/400 

### ISSUE THREAD

**Issue by ironxu** [aviloria/ScreenCaptureServer#1]
captureScreenRect() Invalid rect size (1920x1080), or target image was not initialized!

![pic1](https://user-images.githubusercontent.com/38871684/50514855-e81f6d00-0adb-11e9-893f-7f24217e0888.png)

![pic2](https://user-images.githubusercontent.com/38871684/50514862-ef467b00-0adb-11e9-978a-31543bee8f98.png)

**and VS2015  error:**

C2679 Binary "+=" : "const STD ::chrono::duration>" type of right operand operator (or no acceptable conversion) was not found (ScreenCaptureServer c: program files (x86)\ Microsoft visual studio 14.0\vc\include\chrono 769)

May I ask how to solve this problem? thank you

**Comment by aviloria** [comment]
Hi ironxu,

First of all, thanks a lot for reporting. I have fixed an stupid bug thanks to your report, so -hopefuly- you will now could run the server.

About the VS2015 C2679 error, I couldn't reproduce it on VS2017... and I couldn't find a direct usage of operator "+=" with a std::chrono::duration object on the right side on the code... My best bet is a problem on main.cpp, line 306:
```
dAvgTimeBetweenFrames += dExpectedTimeBetweenFrames * (timeSpan.count() - dAvgTimeBetweenFrames);
```
But std::chono::duration::count() method should return a number... It's annoying.
Please, let me check it on a VS2015, but I'll need a few days to do that.

Please, let me know if the fix I made is useful for you.

**Comment by ironxu** [comment]
Resolved.
